# Ejercicio 1

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import re

In [13]:
# Expresión regular 
regex = r"\w+|[^\w\s]"

# Nuestra frase de trabajo
frase = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
tokens = re.findall(regex, frase)
frase = " ".join(tokens)

# Dividimos la frase en palabras
palabras = frase.split()

# Creamos un codificador One-Hot
onehot_encoder = OneHotEncoder(sparse_output=False)

# Ajustamos el codificador One-Hot a nuestras palabras
onehot_encoded = onehot_encoder.fit_transform(np.array(palabras).reshape(-1, 1))

# Imprimimos el resultado
print(onehot_encoded)

# Imprimimos cómo se codificó cada palabra
for i, palabra in enumerate(palabras):
    print(f"La palabra '{palabra}' se codificó como: {onehot_encoded[i]}")

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
La palabra 'Lorem' se codificó como: [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
La palabra 'ipsum' se codificó como: [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
La palabra 'dolor' se codificó como: [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
La palabra 'sit' se codificó como: [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
La palabra 'amet' se codificó como: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
La palabra ',' se codificó como: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
La palabra 'consectetur' se codificó como: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
La palabra 'adipiscing' se codificó como: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
La palabra 'elit' se codificó como: [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
La palabra '.' se codificó como: [0. 1. 0. 0.

# Ejercicio 2

#### Texto del Ministerio de Turismo.

In [14]:
import pandas as pd

import requests
from bs4 import BeautifulSoup

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait

In [15]:
with webdriver.Firefox() as driver:

    # Abrir la página de El Ministerio de Turismo y Deportes de la Nación
    driver.get("https://tableros.yvera.tur.ar/")
    wait = WebDriverWait(driver, 10)
    
    # Clickeaamos en la imagen que dice "Indicadores ODS (Objetivos de Desarrollo Sostenible)"
    driver.find_element(By.XPATH, "/html/body/d-article/div[2]/div/div/div[17]/a/img").click()

    # Obtenemos la URL de la página a la cual fuimos redirigidos
    current_url = driver.current_url
    
    
    # Extraigo los valores de los tableros y los guardo en una tabla
    response = requests.get(current_url, verify=False)
    
    soup = BeautifulSoup(response.text, 'html.parser')
    
    if response.status_code == 200:
        html = response.text
        summary_div = soup.find('div', {'id': 'shiny-tab-summary'})

        data = {
            'Texto': [],
            'Numero': []
        }

    if summary_div:
        relevant_divs = summary_div.find_all('div', {'class': 'col-sm-4'})
        div = relevant_divs[0]
        cubos = []
        for div in relevant_divs:
          p_elements = div.find_all('p')

          if (len(p_elements)) > 3:
            cubos.append(p_elements[:2])
            cubos.append(p_elements[3:5])

          else:
            p_element = p_elements[:2]
            cubos.append(p_element)

        for cubo in cubos:
          texto = cubo[1].get_text(strip=True)
          data['Texto'].append(texto)
          numero = cubo[0].get_text(strip=True)
          data['Numero'].append(numero)

    df = pd.DataFrame(data)    
    
    # Extraigo la metodología y la imprimo
    html = response.text
    soup = BeautifulSoup(html, 'html.parser')

    box_body_divs = soup.find_all('div', {'class': 'box-body'})

    if box_body_divs:
      div = box_body_divs[-1]
      texto = ""
      for child in div.children:
        if child.name == 'p':
          texto += child.get_text(strip=True) + "\n"
        elif child.name == 'b':
          texto += child.get_text(strip=True) + "\n"
        elif child.name == 'ul':
          for p in child.find_all('p'):
            for b in ul_child.find_all('b'):
              texto += b.get_text(strip=True) + "\n"

c:\Users\src4\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tableros.yvera.tur.ar'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


#### texto obtenido de documento PROYECTO DE LEY TURISMO SOCIAL 2004.pdf

In [19]:
from pdf2image import convert_from_path

In [23]:
# Ruta al archivo PDF
archivo_pdf = 'archivos\\PROYECTO DE LEY TURISMO SOCIAL 2004.pdf'

In [24]:
# Convierte el PDF en una lista de imágenes
imagenes = convert_from_path(archivo_pdf)

# Guarda las imágenes
for i, imagen in enumerate(imagenes):
    imagen.save('pagina{}.png'.format(i), 'PNG')

PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

In [ ]:
for j in range(i+1):
  # Ruta a la imagen
  archivo_imagen = 'pagina{}.png'.format(j)

  # Abre la imagen
  imagen = Image.open(archivo_imagen)

  # Usa pytesseract para convertir la imagen en texto
  # Especificamos el idioma del documento:
  texto = pytesseract.image_to_string(imagen, lang="eng+spa+fra")

  # Imprime el texto extraído
  print(texto)